name: 'File Generator'
description: 'Generate files into specified directories and sub-directories.'
author: 'Manjeetsinh Alonja'
branding:
  icon: 'git-pull-request'
  color: 'purple'
inputs:
  WORK_DIR:
    description: 'Working directory to start with. For root it is ./'
    required: true
  FILE_NAME:
    description: 'Name of the file which needs to be created.'
    required: true
  FILE_CONTENT:
    description: 'Content of the file which needs to be added.'
    required: true
  OVERRIDE_CONTENT:
    description: 'Flag to override the content of existing file or not. Valid values are "true" or "false"'
    default: false
  RECURSIVE:
    description: 'Recursive mode to generate files in multiple directories.'
    default: false
  RECURSIVE_DEPTH:
    description: 'Recursive search depth. Please pass numbers. 1 means in all directories which are in WORK_DIR, it will not include subdirectories of those directories.'
    default: 1
  RECURSIVE_INCLUDE_WORK_DIR:
    description: 'Pass true if you want to create file in the work dir as well.'
    default: false
  GIT_PUSH_USER_NAME:
    description: 'User name of the bot user'
    default: 'github-actions[bot]'
  GIT_PUSH_USER_EMAIL:
    description: 'Email of the bot user'
    default: 'github-actions[bot]@users.noreply.github.com'
  GIT_COMMIT_MESSAGE:
    description: 'Commit message'
    default: 'file-generator: automated action'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_WORK_DIR: ${{ input.WORK_DIR }}
    INPUT_FILE_NAME: ${{ input.FILE_NAME }}
    INPUT_FILE_CONTENT: ${{ input.FILE_CONTENT }}
    INPUT_OVERRIDE_CONTENT: ${{ input.OVERRIDE_CONTENT }}
    INPUT_RECURSIVE: ${{ input.RECURSIVE }}
    INPUT_RECURSIVE_DEPTH: ${{ input.RECURSIVE_DEPTH }}
    INPUT_RECURSIVE_INCLUDE_WORK_DIR: ${{ input.RECURSIVE_INCLUDE_WORK_DIR }}
    INPUT_GIT_PUSH_USER_NAME: ${{ input.GIT_PUSH_USER_NAME }}
    INPUT_GIT_PUSH_USER_EMAIL: ${{ input.GIT_PUSH_USER_EMAIL }}
    INPUT_GIT_COMMIT_MESSAGE: ${{ input.GIT_COMMIT_MESSAGE }}
