name: 'File Generator'
description: 'Generate files into specified directories and sub-directories.'
author: 'Manjeetsinh Alonja'
branding:
  icon: 'git-pull-request'
  color: 'purple'
inputs:
  WORK_DIR:
    description: 'Working directory to start with. For root it is ./'
    required: true
  FILE_NAME:
    description: 'Name of the file which needs to be created.'
    required: true
  FILE_CONTENT:
    description: 'Content of the file which needs to be added.'
    required: true
  OVERRIDE_CONTENT:
    description: 'Flag to override the content of existing file or not. Valid values are "true" or "false"'
    default: false
  RECURSIVE:
    description: 'Recursive mode to generate files in multiple directories.'
    default: false
  RECURSIVE_DEPTH:
    description: 'Recursive search depth. Please pass numbers. 1 means in all directories which are in WORK_DIR, it won't include subdirectories of those directories.'
    default: 1
runs:
  using: 'docker'
  image: 'Dockerfile'